title: ARC Helm chart repo
description: A chart repo for storing charts.
theme: minima
url: "https://arc-entertainment.github.io/arc-helm"
repo_name: arc

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore